### ISSUE TITLE
Action is generating every model with Microsoft Graph

### ISSUE THREAD

**Issue by brianmuse** [microsoft/setup-kiota#173]
For the below configuration it seems to be generating every model in MS Graph, and not just the necessary models. (see screenshot)

<img width="327" alt="Image" src="https://github.com/user-attachments/assets/c66e0343-fb99-42e9-a2c2-99ced1cb85d0" />

There was a bug filed and fixed a while back in the main kiota repo (https://github.com/microsoft/kiota/issues/2543), however for whatever reason this repo seems susceptible to the same outcome. And so I'm wondering if the setup action is somehow using an older version of kiota. 

```yaml
name: Generate Microsoft Graph SDK

on:
  workflow_dispatch: # Allow manual triggers

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Kiota
        uses: microsoft/setup-kiota@v0.5.0

      - name: Create SDK Directories
        run: |
          mkdir -p core/msgraph_sdk/v1
          mkdir -p core/msgraph_sdk/beta

      - name: Download OpenAPI Specs
        run: |
          curl -L https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml -o msgraph-openapi-v1.yaml
          curl -L https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/beta/openapi.yaml -o msgraph-openapi-beta.yaml

      - name: Generate V1 SDK
        run: |
          kiota generate \
            --language python \
            --openapi msgraph-openapi-v1.yaml \
            --output core/msgraph_sdk/v1 \
            --namespace-name msgraph_sdk.v1 \
            --include-path "/me" \
            --clean-output

      - name: Generate Beta SDK
        run: |
          kiota generate \
            --language python \
            --openapi msgraph-openapi-beta.yaml \
            --output core/msgraph_sdk/beta \
            --namespace-name msgraph_sdk.beta \
            --include-path "/me" \
            --clean-output

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update Microsoft Graph SDK for v1 and beta"
          title: "Update Microsoft Graph SDK (v1 and beta)"
          body: |
            This PR updates the Microsoft Graph SDK using Kiota.
          branch: update-msgraph-sdk
          delete-branch: true
          base: main
```
