### ISSUE TITLE
Feedback request: additional tasks to map commands

### ISSUE THREAD

**Issue by baywet** [microsoft/setup-kiota#4]
We want to hear from you! If you'd like additional actions that map to the kiota commands, please upvote this issue. Don't hesitate to comment to provide additional context as well.

e.g.

```yaml
steps:
  - uses: actions/checkout@v3
  - uses: microsoft/setup-kiota@v0.5.0
  - uses: microsoft/kiota-update@v0.5.0
```

would update all clients in the workspace

```yaml
steps:
  - uses: actions/checkout@v3
  - uses: microsoft/setup-kiota@v0.5.0
  - uses: microsoft/kiota-generate@v0.5.0
    with:
      description: https://foo.bar/baz.yml
      outputPath: /src
```

would generate a new client

etc...
